#!/bin/sh

# stash any unstaged changes
git stash -q --keep-index

./gradlew test
./gradlew spotbugsMain
./gradlew pmdMain


# store the last exit code in a variable
RESULT=$?

# unstash the unstashed changes
git stash pop -q

# return the './gradlew test' exit code
exit $RESULT
